import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createWorld } from './world.js';
import { createCharacter } from './character.js';
import { Simulation, SAVE_KEY, validateSave } from './simulation.js';
import { parseDescription, analyzePhoto, ageLabels } from './appearance.js';
import { planCommand, actionLabels } from './planner.js';
import { Ambience } from './audio.js';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4200);}
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(error){$('loading').innerHTML='<h2>Нужна поддержка WebGL 2</h2><p>Включите аппаратное ускорение или откройте игру в современном Chrome, Edge, Firefox или Safari.</p>';throw error;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.22;renderer.outputColorSpace=THREE.SRGBColorSpace;$('world').appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e7ecdf');scene.fog=new THREE.Fog('#e7ecdf',65,140);
const camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.1,220);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=5;controls.maxDistance=87;controls.maxPolarAngle=Math.PI*.465;controls.minPolarAngle=.12;controls.target.set(0,0,0);controls.enablePan=true;controls.screenSpacePanning=false;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};
const hemi=new THREE.HemisphereLight('#e6eedb','#9a9b80',2.6);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff0ce',3.7);sun.position.set(-18,35,22);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-38;sun.shadow.camera.right=38;sun.shadow.camera.top=34;sun.shadow.camera.bottom=-34;sun.shadow.camera.far=100;sun.shadow.bias=-.0005;sun.shadow.normalBias=.035;sun.shadow.radius=3;scene.add(sun);scene.add(sun.target);
const surroundings=new THREE.Mesh(new THREE.PlaneGeometry(1000,1000),new THREE.MeshStandardMaterial({color:'#dce2d2',roughness:1}));surroundings.rotation.x=-Math.PI/2;surroundings.position.y=-.75;surroundings.receiveShadow=true;scene.add(surroundings);
const world=createWorld(scene);let saved=null,saveWarning='';try{const raw=localStorage.getItem(SAVE_KEY);if(raw){saved=validateSave(JSON.parse(raw));if(!saved)saveWarning='Сохранение повреждено. Открыт новый квартал.';}}catch{saveWarning='Не удалось прочитать сохранение. Открыт новый квартал.';}
const sim=new Simulation(world.obstacles,world.objects,saved),models=new Map();let selected=null,follow=false,mode='text',spec=null,photoFile=null,photoURL=null,pendingPlan=null,fps=60,maxPeople=20,quality='auto',elapsed=0,uiTick=0,saveTick=0,night=0,rainAmount=0,weatherTick=0;
sim.event=(message,p)=>{if(p.id===selected)toast(message);};
function syncModels(){for(const p of sim.people)if(!models.has(p.id)){const model=createCharacter(p);model.root.traverse(o=>{o.userData.personId=p.id;});scene.add(model.root);models.set(p.id,model);}}
syncModels();
function overview(){follow=false;camera.position.set(innerWidth<700?44:42,innerWidth<700?43:35,innerWidth<700?54:46);controls.target.set(innerWidth<700?0:0,0,-1);controls.update();}
overview();
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(sim.snapshot()));$('save-status').textContent='✓ Мир сохранён на этом устройстве';return true;}catch{$('save-status').textContent='! Сохранение недоступно';toast('Браузер не разрешил сохранение. Проверьте настройки хранилища.');return false;}}
function selectedPerson(){return sim.people.find(p=>p.id===selected);}
function traitLabels(p){return [p.personality.sociability>.65?'Общительный':p.personality.sociability<.4?'Сдержанный':'Дружелюбный',p.personality.energy>.7?'Энергичный':'Спокойный',p.personality.curiosity>.65?'Любознательный':'Внимательный',...p.interests.map(i=>({reading:'Книги',parks:'Прогулки',coffee:'Кофе',running:'Пробежки'}[i]||i))];}
function select(id){selected=id;const p=selectedPerson();if(!p)return;$('residents').hidden=true;$('person-panel').hidden=false;for(const [pid,m]of models)m.ring.visible=pid===id;renderPerson(true);$('person-panel').scrollTop=0;}
function renderPerson(full=false){const p=selectedPerson();if(!p)return;const can=p.source!=='default';if(full){$('person-panel').innerHTML=`<div class="panel-heading"><h2>${esc(p.name)}</h2><button class="icon-button" id="person-close" aria-label="Закрыть карточку">×</button></div><span class="source">${{default:'Житель квартала',text:'Создан по описанию',image:'Создан по изображению'}[p.source]} · ${ageLabels[p.appearance.ageGroup]}</span><div class="person-action"><span id="p-action"></span><small id="p-reason"></small></div><div class="meter-label"><span>Настроение</span><span id="p-mood-label"></span></div><div class="meter"><span id="p-mood"></span></div><div class="meter-label"><span>Энергия</span><span id="p-energy-label"></span></div><div class="meter"><span id="p-energy"></span></div><div class="traits">${traitLabels(p).map(t=>`<span>${esc(t)}</span>`).join('')}</div>${can?`<div class="person-controls"><div class="button-row"><button id="run-toggle" class="secondary">${p.run?'Бежать':'Идти'}</button><button id="follow" class="secondary">${follow?'Не следить':'Следовать'}</button></div><div class="action-grid">${[['read','Читать'],['rest','Посидеть'],['phone','Телефон'],['drink','Кофе'],['eat','Поесть'],['shop','Книжный'],['walk','Гулять'],['stop','Стоп'],['auto','Свои дела']].map(([a,label])=>`<button data-action="${a}">${label}</button>`).join('')}</div><div class="command-box"><input id="command" aria-label="Команда персонажу" placeholder="Найди лавочку и почитай…" maxlength="300"><button id="send-command" aria-label="Показать план">↑</button></div><p class="control-hint">Нажмите на землю, чтобы задать путь. Нажмите на лавочку или столик, чтобы занять свободное место. Для разговора выберите другого человека.</p></div>`:`<button class="secondary full" id="follow">${follow?'Не следить':'Наблюдать поближе'} <span>↗</span></button><p class="control-hint">Этот житель самостоятельно выбирает, чем заняться. Создайте своего человека, чтобы направлять его.</p>`}<div id="p-memory" class="memory"></div>`;
      $('person-close').onclick=()=>{selected=null;follow=false;$('person-panel').hidden=true;for(const m of models.values())m.ring.visible=false;};
      $('follow').onclick=()=>{follow=!follow;if(follow){controls.target.set(p.x,.8,p.z);camera.position.set(p.x+7,7,p.z+10);}renderPerson(true);};
      if(can){$('run-toggle').onclick=()=>{p.run=!p.run;renderPerson(true);};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{sim.command(p.id,[{action:b.dataset.action,duration:b.dataset.action==='read'?Infinity:undefined}]);renderPerson();});$('send-command').onclick=()=>command($('command').value);$('command').onkeydown=e=>{if(e.key==='Enter')command(e.target.value);};}
    }
    $('p-action').textContent=p.phase==='travel'?(p.action==='run'||p.run?'Бежит':'Идёт')+({read:' к лавочке с книгой',rest:' к свободному месту',drink:' в кафе',eat:' на обед',shop:' в книжный',home:' домой',work:' на работу',talk:' к знакомому',wait:' к остановке'}[p.action]||' по кварталу'):(actionLabels[p.action]||'Осматривается');$('p-reason').textContent=p.reason;$('p-mood-label').textContent=p.needs.mood>.65?'Хорошее':p.needs.mood>.35?'Спокойное':'Задумчивое';$('p-mood').style.width=Math.round(p.needs.mood*100)+'%';$('p-energy-label').textContent=Math.round(p.needs.energy*100)+'%';$('p-energy').style.width=Math.round(p.needs.energy*100)+'%';$('p-memory').textContent=p.memory.length?'Недавно: '+p.memory.slice(-2).map(m=>m.text.toLowerCase()).join(' · '):'Новая маленькая история начинается.';
}
let residentsSignature='';
function renderResidents(){const signature=sim.people.map(p=>p.id+':'+p.name).join('|');if(signature!==residentsSignature){residentsSignature=signature;$('residents-list').innerHTML=sim.people.map(p=>`<button class="resident-row" data-person="${p.id}"><span class="resident-avatar" style="background:${/^#[a-f0-9]{6}$/i.test(p.appearance.clothing.outerwear)?p.appearance.clothing.outerwear:'#7a8b76'}">${esc(p.name[0])}</span><span><strong>${esc(p.name)} ${p.source==='default'?'':'· ваш персонаж'}</strong><small data-status="${p.id}"></small></span></button>`).join('');document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>select(Number(b.dataset.person)));}for(const p of sim.people){const el=document.querySelector(`[data-status="${p.id}"]`);if(el)el.textContent=actionLabels[p.action]||'Гуляет';}}
function command(text){const p=selectedPerson();if(!p||p.source==='default')return;const plan=planCommand(text,sim.people,p.id);if(plan.error){toast(plan.error);return;}pendingPlan={id:p.id,steps:plan.steps};$('plan-list').innerHTML=plan.steps.map(s=>`<li>${esc(s.label)}</li>`).join('');$('plan-note').textContent=plan.note||'Если все места заняты, подожду рядом и попробую ещё раз.';$('plan-dialog').showModal();}
$('execute-plan').onclick=()=>{if(pendingPlan){sim.command(pendingPlan.id,pendingPlan.steps);toast('Хорошо. Уже иду.');renderPerson();}pendingPlan=null;$('plan-dialog').close();};$('plan-close').onclick=()=>$('plan-dialog').close();
// Picking uses character meshes first, then a ground plane. Dragging never issues a move.
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),groundPlane=new THREE.Plane(new THREE.Vector3(0,1,0),-.15),hit=new THREE.Vector3();let down=null;
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===0)down={x:e.clientX,y:e.clientY,time:performance.now()};});
renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6||performance.now()-down.time>450){down=null;return;}down=null;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects([...models.values()].map(m=>m.root),true).filter(h=>h.object.visible&&h.object.parent?.visible&&h.object.userData.personId);const p=selectedPerson();if(hits.length){const id=hits[0].object.userData.personId;if(p&&p.source!=='default'&&id!==p.id){pendingPlan={id:p.id,steps:[{action:'talk',targetId:id}]};$('plan-list').innerHTML=`<li>Подойти к ${esc(sim.people.find(q=>q.id===id).name)} и поговорить</li>`;$('plan-note').textContent='Занятый житель может лишь поздороваться.';$('plan-dialog').showModal();}else select(id);return;}
  if(p&&p.source!=='default'&&ray.ray.intersectPlane(groundPlane,hit)){if(Math.abs(hit.x)>23||Math.abs(hit.z)>17){toast('Это за пределами квартала. Выберите место ближе.');return;}const seat=sim.objects.find(o=>Math.hypot(o.x-hit.x,o.z-hit.z)<.9);if(seat){if(seat.owner&&seat.owner!==p.id){toast('Это место занято. Найду другое рядом.');sim.command(p.id,[{action:seat.type==='cafe'?'drink':'rest'}]);}else{sim.command(p.id,[{action:seat.type==='cafe'?'drink':'rest',seatId:seat.id}]);}}else sim.command(p.id,[{action:p.run?'run':'walk',point:{x:hit.x,z:hit.z}}]);renderPerson();}
});
// Creation is a two-stage flow: local recognition, editable structured parameters, then spawn.
const previewScene=new THREE.Scene();const previewCamera=new THREE.PerspectiveCamera(32,1,.1,30);previewCamera.position.set(3,1.9,4.8);previewCamera.lookAt(0,.9,0);previewScene.add(new THREE.HemisphereLight('#fff5de','#a7ad96',3));const previewLight=new THREE.DirectionalLight('#fff3de',3);previewLight.position.set(-3,5,4);previewScene.add(previewLight);let previewRenderer=null,previewModel=null;
const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(.8,.84,.07,64),new THREE.MeshStandardMaterial({color:'#d9dfca',roughness:1}));pedestal.position.y=.035;previewScene.add(pedestal);
function updatePreview(){if(!spec)return;readFields();if(previewModel)previewScene.remove(previewModel.root);previewModel=createCharacter(spec);previewScene.add(previewModel.root);$('preview-name').textContent=spec.name;$('preview-summary').textContent=traitLabels(spec).slice(0,4).join(' · ');$('recognized-json').textContent=JSON.stringify({appearance:spec.appearance,personality:spec.personality,interests:spec.interests,initialIntent:spec.initialIntent},null,2);}
function fillFields(){const a=spec.appearance;$('c-name').value=spec.name;$('c-age').value=a.ageGroup;$('c-height').value=a.height;$('c-body').value=a.bodyType;$('c-hair-length').value=a.hair.length;$('c-hair-style').value=a.hair.style;$('c-hair').value=a.hair.color;$('c-skin').value=a.skin;$('c-top').value=a.clothing.outerwear;$('c-bottom').value=a.clothing.bottom;$('c-social').value=spec.personality.sociability;$('c-energy').value=spec.personality.energy;$('c-intent').value=spec.initialIntent.action;}
function readFields(){if(!spec)return;spec.name=$('c-name').value.trim()||'Саша';const a=spec.appearance;a.ageGroup=$('c-age').value;a.height=$('c-height').value;a.bodyType=$('c-body').value;a.hair.length=$('c-hair-length').value;a.hair.style=$('c-hair-style').value;a.hair.color=$('c-hair').value;a.skin=$('c-skin').value;a.clothing.outerwear=$('c-top').value;a.clothing.bottom=$('c-bottom').value;spec.personality.sociability=Number($('c-social').value);spec.personality.energy=Number($('c-energy').value);spec.initialIntent.action=$('c-intent').value;spec.initialIntent.duration=spec.initialIntent.action==='read'?'until_changed':'automatic';spec.initialIntent.location=['drink','eat'].includes(spec.initialIntent.action)?'cafe':['read','rest'].includes(spec.initialIntent.action)?'park_bench':'park';}
document.querySelectorAll('#recognized input,#recognized select').forEach(e=>e.addEventListener('input',updatePreview));
function setMode(next){mode=next;$('tab-text').classList.toggle('active',mode==='text');$('tab-image').classList.toggle('active',mode==='image');$('text-entry').hidden=mode!=='text';$('image-entry').hidden=mode!=='image';$('analyze').innerHTML=(mode==='text'?'Разобрать описание':'Подобрать внешность')+' <span>→</span>';$('recognized').hidden=true;$('add-person').disabled=true;$('creator-error').textContent='';spec=null;}
$('tab-text').onclick=()=>setMode('text');$('tab-image').onclick=()=>setMode('image');
$('create').onclick=()=>{if(sim.people.length>=maxPeople){toast('Квартал пока заполнен: лимит для этого устройства — '+maxPeople+' жителей.');return;}$('creator').showModal();if(!previewRenderer){previewRenderer=new THREE.WebGLRenderer({alpha:true,antialias:true});previewRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));previewRenderer.toneMapping=THREE.ACESFilmicToneMapping;previewRenderer.toneMappingExposure=1.2;$('preview').appendChild(previewRenderer.domElement);}if(!previewModel){const initial=parseDescription('Девушка с короткими тёмными волосами в зелёной куртке');previewModel=createCharacter(initial);previewScene.add(previewModel.root);}resizePreview();};
function resizePreview(){if(!previewRenderer)return;const rect=$('preview').getBoundingClientRect();if(!rect.width)return;previewRenderer.setSize(rect.width,rect.height,false);previewCamera.aspect=rect.width/rect.height;previewCamera.updateProjectionMatrix();}
new ResizeObserver(resizePreview).observe($('preview'));
$('photo').onchange=()=>{photoFile=$('photo').files[0];$('recognized').hidden=true;$('add-person').disabled=true;spec=null;if(photoURL){URL.revokeObjectURL(photoURL);photoURL=null;}if(photoFile&&['image/jpeg','image/png','image/webp'].includes(photoFile.type)&&photoFile.size<=10*1024*1024){photoURL=URL.createObjectURL(photoFile);document.querySelector('.upload').style.backgroundImage=`url("${photoURL}")`;document.querySelector('.upload').classList.add('has-photo');$('upload-label').textContent=photoFile.name;}else{$('upload-label').textContent='Выберите JPG, PNG или WebP до 10 МБ';document.querySelector('.upload').style.backgroundImage='none';document.querySelector('.upload').classList.remove('has-photo');}};
$('analyze').onclick=async()=>{const button=$('analyze');button.disabled=true;$('creator-error').textContent='';try{
  if(mode==='text'){const text=$('description').value.trim();if(!text)throw new Error('Добавьте хотя бы пару слов о будущем жителе.');spec=parseDescription(text,'text');}
  else{if(!photoFile)throw new Error('Сначала выберите изображение.');const colors=await analyzePhoto(photoFile);spec=parseDescription($('photo-personality').value,'image');spec.appearance.hair.color=colors.hair;spec.appearance.skin=colors.skin;spec.appearance.clothing.outerwear=colors.top;}
  fillFields();$('recognized').hidden=false;$('add-person').disabled=false;updatePreview();if(mode==='image')$('creator-error').textContent='Палитра приблизительная: фон и освещение могут влиять на цвет. Проверьте образ справа.';
}catch(e){$('creator-error').textContent=e.message;$('add-person').disabled=true;}finally{button.disabled=false;}};
$('add-person').onclick=()=>{if(!spec||sim.people.length>=maxPeople)return;readFields();const p=sim.add(spec);syncModels();$('creator').close();select(p.id);save();toast(p.name+' теперь живёт в квартале');controls.target.set(p.x,.3,p.z);camera.position.set(p.x+9,10,p.z+15);};
// Time, weather, menus and keyboard controls.
document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{sim.speed=Number(b.dataset.speed);document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',Number(x.dataset.speed)===sim.speed));});
$('overview').onclick=overview;document.querySelector('.brand').onclick=e=>{e.preventDefault();overview();};$('zoom-in').onclick=()=>camera.position.copy(controls.target.clone().add(camera.position.clone().sub(controls.target).multiplyScalar(.8)));$('zoom-out').onclick=()=>camera.position.copy(controls.target.clone().add(camera.position.clone().sub(controls.target).multiplyScalar(1.2)));
function hideUI(hide){$('ui').hidden=hide;$('show-ui').hidden=!hide;}$('hide-ui').onclick=()=>hideUI(true);$('show-ui').onclick=()=>hideUI(false);
$('residents-toggle').onclick=()=>{$('residents').hidden=!$('residents').hidden;if(!$('residents').hidden){$('person-panel').hidden=true;renderResidents();}};$('residents-close').onclick=()=>$('residents').hidden=true;
$('settings').onclick=()=>{$('time-slider').value=sim.minute;$('weather-select').value=sim.weather;$('settings-dialog').showModal();};$('settings-close').onclick=()=>$('settings-dialog').close();$('time-slider').oninput=e=>{sim.minute=Number(e.target.value);};$('weather-select').onchange=e=>{sim.weather=e.target.value;weatherTick=0;};$('weather').onclick=()=>{sim.weather=['clear','cloudy','rain'][(['clear','cloudy','rain'].indexOf(sim.weather)+1)%3];weatherTick=0;toast({clear:'Небо проясняется',cloudy:'Над кварталом собираются облака',rain:'Начинается небольшой дождь'}[sim.weather]);};
function setQuality(value){quality=value;const low=value==='low'||value==='auto'&&fps<28;renderer.setPixelRatio(low?1:Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=!low;maxPeople=low?16:20;}
$('quality').onchange=e=>setQuality(e.target.value);$('save-now').onclick=()=>{if(save())toast('Мир сохранён');};$('reset-world').onclick=()=>$('reset-dialog').showModal();$('reset-cancel').onclick=()=>$('reset-dialog').close();$('reset-confirm').onclick=()=>{try{localStorage.removeItem(SAVE_KEY);}catch{toast('Не удалось очистить сохранение');return;}location.reload();};
const audio=new Ambience();$('sound').onclick=async()=>{try{const on=await audio.toggle();$('sound').style.background=on?'#dae6ce':'';$('sound').title=on?'Выключить звуки города':'Включить звуки города';$('sound').setAttribute('aria-label',$('sound').title);toast(on?'Слышны птицы и далёкий шум улицы':'Звуки выключены');}catch{toast('Звук недоступен в этом браузере');}};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.code==='KeyH')hideUI(!$('ui').hidden);if(e.code==='Space'){e.preventDefault();document.querySelector(`[data-speed="${sim.speed===0?1:0}"]`).click();}if(e.code==='Escape'){$('person-panel').hidden=true;$('residents').hidden=true;selected=null;follow=false;for(const m of models.values())m.ring.visible=false;}});
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);resizePreview();});window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
function drawMap(){const c=$('minimap'),ctx=c.getContext('2d');ctx.fillStyle='#e3e7d8';ctx.fillRect(0,0,200,126);ctx.fillStyle='#a8b496';ctx.fillRect(9,35,91,62);ctx.fillStyle='#c9c4ae';ctx.fillRect(114,33,71,65);ctx.fillStyle='#afb7a5';ctx.fillRect(0,101,200,20);ctx.strokeStyle='#edeedc';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(10,67);ctx.lineTo(99,67);ctx.moveTo(72,34);ctx.lineTo(72,97);ctx.stroke();ctx.fillStyle='#b9b7a4';for(const [x,w]of [[16,35],[56,38],[112,33],[151,35]])ctx.fillRect(x,7,w,24);for(const p of sim.people){ctx.beginPath();ctx.arc((p.x+24)/48*200,(p.z+18)/36*126,p.id===selected?3.4:2,0,Math.PI*2);ctx.fillStyle=p.id===selected?'#e8b677':p.source==='default'?'#5e7d60':'#b17b54';ctx.fill();}}
const skyDay=new THREE.Color('#e7ecdf'),skyNight=new THREE.Color('#253d48'),skyRain=new THREE.Color('#a7b6b0');let previous=performance.now(),frameCount=0,fpsTime=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-previous)/1000,.1);previous=now;if(document.hidden)return;elapsed+=dt;sim.update(dt);uiTick+=dt;saveTick+=dt;weatherTick+=dt*sim.speed;frameCount++;fpsTime+=dt;if(fpsTime>2){fps=frameCount/fpsTime;frameCount=0;fpsTime=0;if(quality==='auto'&&elapsed>12&&fps<26){setQuality('auto');} }
  const phase=(sim.minute-360)/1440*Math.PI*2,light=Math.max(0,Math.sin(phase));const nightTarget=1-THREE.MathUtils.smoothstep(light,0,.23);night=THREE.MathUtils.damp(night,nightTarget,1,dt);rainAmount=THREE.MathUtils.damp(rainAmount,sim.weather==='rain'?1:0,1,dt);
  sun.position.set(Math.cos(phase)*34,Math.max(2,light*40),17);sun.intensity=THREE.MathUtils.damp(sun.intensity,(.1+light*3.7)*(sim.weather==='clear'?1:.5),1.5,dt);hemi.intensity=2.5-night*1.8;sun.color.set(night>.5?'#b4c7df':light<.3?'#f4b77c':'#fff0ce');scene.background.copy(skyDay).lerp(skyNight,night).lerp(skyRain,rainAmount*.45);scene.fog.color.copy(scene.background);
  world.setFocus(follow?selectedPerson():null,camera.position);world.update(elapsed,dt,night,rainAmount);for(const p of sim.people){const model=models.get(p.id);model.update(p,dt*sim.speed,sim.elapsed,Math.hypot(camera.position.x-p.x,camera.position.z-p.z),sim.weather);}
  if(follow){const p=selectedPerson();if(p){const target=new THREE.Vector3(p.x,.8,p.z),delta=target.clone().sub(controls.target).multiplyScalar(Math.min(1,dt*4));controls.target.add(delta);camera.position.add(delta);}}controls.update();renderer.render(scene,camera);
  if($('creator').open&&previewRenderer&&previewModel){previewModel.root.rotation.y=Math.sin(elapsed*.4)*.4;previewRenderer.render(previewScene,previewCamera);}
  if(uiTick>.45){uiTick=0;const h=Math.floor(sim.minute/60),m=Math.floor(sim.minute%60);$('clock').textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');$('day').textContent='День '+sim.day;$('population').textContent=sim.people.length+' жителей рядом';$('weather').innerHTML={clear:'☀ <span>Ясно, +22°</span>⌄',cloudy:'☁ <span>Облачно, +18°</span>⌄',rain:'☂ <span>Дождь, +16°</span>⌄'}[sim.weather];$('scene-caption').textContent=sim.speed===0?'Маленькая пауза. Мир подождёт.':night>.5?'Окна светятся. Город становится тише.':sim.weather==='rain'?'Дождь пахнет липами и мокрым асфальтом.':'Обычный день. Особенное место.';if(selected&&!$('person-panel').hidden)renderPerson();if(!$('residents').hidden)renderResidents();drawMap();$('performance').textContent=`${Math.round(fps)} кадров/с · ${sim.people.length}/${maxPeople} жителей · ${renderer.info.render.calls} вызовов отрисовки`;
  }
  if(saveTick>10){saveTick=0;save();}if(weatherTick>300){weatherTick=0;sim.weather=sim.weather==='clear'?'cloudy':sim.weather==='cloudy'?(Math.random()>.5?'rain':'clear'):'cloudy';}
}
requestAnimationFrame(animate);setTimeout(()=>{$('loading').style.opacity='0';setTimeout(()=>$('loading').remove(),500);if(saveWarning)toast(saveWarning);},250);
// Read-only diagnostics for local verification. State-changing operations stay in the UI.
window.quarter={getState:()=>sim.snapshot(),getDiagnostics:()=>({fps,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,people:sim.people.length,occupied:sim.objects.filter(o=>o.owner).map(o=>({seat:o.id,person:o.owner})),obstacles:world.obstacles,webgl:renderer.capabilities.isWebGL2}),project:(x,y,z)=>{const p=new THREE.Vector3(x,y,z).project(camera);return {x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2};}};
